# Generated by Django 4.2.4 on 2023-08-18 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_pricing_price'),
        ('content', '0002_alter_category_options_alter_category_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='pricing_tiers',
            field=models.ManyToManyField(blank=True, to='accounts.pricing'),
        ),
    ]
