# Generated by Django 4.2.4 on 2023-08-19 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_course_pricing_tiers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_url',
            field=models.CharField(max_length=500),
        ),
    ]
