# Generated by Django 4.2.4 on 2023-08-18 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_pricing_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricing',
            name='stripe_price_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
